package pojos;
// Generated 06-oct-2016 10:48:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="almazaradb"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String dni;
     private String direccion;
     private String telefono;
     private String poblacion;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombre) {
        this.nombre = nombre;
      
    }
    public Cliente(String nombre, String dni, String direccion, String telefono, String poblacion, Set ventas) {
       this.nombre = nombre;
       this.dni = dni;
       this.direccion = direccion;
       this.telefono = telefono;
       this.poblacion = poblacion;
       this.ventas = ventas;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="dni", length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="direccion", length=70)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="poblacion", length=25)
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


