package pojos;
// Generated 06-oct-2016 10:48:58 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gastos generated by hbm2java
 */
@Entity
@Table(name="gastos"
    ,catalog="almazaradb"
)
public class Gastos  implements java.io.Serializable {


     private Integer idGasto;
     private Date fecha;
     private String concepto;
     private float cantidad;
     private Float precio;
     private float gastos;
     private Float manoObra;

    public Gastos() {
    }

	
    public Gastos(Date fecha, String concepto, float cantidad, float gastos) {
        this.fecha = fecha;
        this.concepto = concepto;
        this.cantidad = cantidad;
        this.gastos = gastos;
    }
    public Gastos(Date fecha, String concepto, float cantidad, float precio, float gastos, float manoObra) {
       this.fecha = fecha;
       this.concepto = concepto;
       this.cantidad = cantidad;
       this.precio = precio;
       this.gastos = gastos;
       this.manoObra = manoObra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idGasto", unique=true, nullable=false)
    public Integer getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(Integer idGasto) {
        this.idGasto = idGasto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="concepto", nullable=false, length=45)
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    
    @Column(name="cantidad", nullable=false, precision=12, scale=0)
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="precio", precision=12, scale=0)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }

    
    @Column(name="gastos", nullable=false, precision=12, scale=0)
    public float getGastos() {
        return this.gastos;
    }
    
    public void setGastos(float gastos) {
        this.gastos = gastos;
    }

    
    @Column(name="manoObra", precision=12, scale=0)
    public Float getManoObra() {
        return this.manoObra;
    }
    
    public void setManoObra(Float manoObra) {
        this.manoObra = manoObra;
    }




}


