package pojos;
// Generated 22-nov-2016 13:00:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="almazaradb"
)
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private Float unidades;
     private float precio;
     private Set ventas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombre, float precio) {
        this.nombre = nombre;
        this.precio = precio;
    }
    public Producto(String nombre, Float unidades, float precio, Set ventas) {
       this.nombre = nombre;
       this.unidades = unidades;
       this.precio = precio;
       this.ventas = ventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProducto", unique=true, nullable=false)
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="unidades", precision=12, scale=0)
    public Float getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Float unidades) {
        this.unidades = unidades;
    }

    
    @Column(name="precio", nullable=false, precision=12, scale=0)
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="producto_has_venta", catalog="almazaradb", joinColumns = { 
        @JoinColumn(name="Producto_idProducto", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Venta_idVenta", nullable=false, updatable=false) })
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


