package pojos;
// Generated 06-oct-2016 10:48:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="almazaradb"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombre;
     private String dni;
     private String direccion;
     private String telefono;
     private String poblacion;
     private boolean subvencionado;
     private Set compras = new HashSet(0);
     private Set cambios = new HashSet(0);
     private Set molturacions = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, boolean subvencionado) {
        this.nombre = nombre;
        this.subvencionado = subvencionado;
    }
    public Proveedor(String nombre, String dni, String direccion, String telefono, String poblacion, boolean subvencionado, Set compras, Set cambios, Set molturacions) {
       this.nombre = nombre;
       this.dni = dni;
       this.direccion = direccion;
       this.telefono = telefono;
       this.poblacion = poblacion;
       this.subvencionado = subvencionado;
       this.compras = compras;
       this.cambios = cambios;
       this.molturacions = molturacions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProveedor", unique=true, nullable=false)
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="dni", length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="direccion", length=70)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="telefono", length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="poblacion", length=25)
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }

    
    @Column(name="subvencionado", nullable=false)
    public boolean isSubvencionado() {
        return this.subvencionado;
    }
    
    public void setSubvencionado(boolean subvencionado) {
        this.subvencionado = subvencionado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getCambios() {
        return this.cambios;
    }
    
    public void setCambios(Set cambios) {
        this.cambios = cambios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getMolturacions() {
        return this.molturacions;
    }
    
    public void setMolturacions(Set molturacions) {
        this.molturacions = molturacions;
    }




}


