/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almazarabarcha.vista;

import java.util.Date;

/**
 *
 * @author Ventura
 */
public class AñadirGasto extends javax.swing.JPanel {

    Date fecha = new Date();
    String concepto = "";
    float cantidad = 0;
    float precio = 0;

    /**
     * Creates new form AñadirGasto
     */
    public AñadirGasto(String lblTitulo, String lblConcepto, String lblPrecio) {
        initComponents();
        this.lblTitulo.setText(lblTitulo);
        this.lblConcepto.setText(lblConcepto);
        this.lblPrecio.setText(lblPrecio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateGasto = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        txtfConcepto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblConcepto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfCantidad = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtfPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        jLabel1.setText("Fecha:");

        txtfConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfConceptoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Insertar");

        lblConcepto.setText("Concepto:");

        jLabel4.setText("Cantidad:");

        txtfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfCantidadKeyReleased(evt);
            }
        });

        lblPrecio.setText("Precio:");

        txtfPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfPrecioKeyReleased(evt);
            }
        });

        jLabel6.setText("€");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulo.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dateGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConcepto)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfConcepto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(lblPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(txtfPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(lblTitulo))
                    .addComponent(dateGasto, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtfConcepto)
                    .addComponent(lblConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio)
                    .addComponent(txtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfConceptoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfConceptoKeyReleased
        fecha = dateGasto.getSelectedDate().getTime();
        concepto = txtfConcepto.getText();
    }//GEN-LAST:event_txtfConceptoKeyReleased

    private void txtfCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfCantidadKeyReleased
        cantidad = Float.parseFloat(txtfCantidad.getText());
    }//GEN-LAST:event_txtfCantidadKeyReleased

    private void txtfPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfPrecioKeyReleased
        precio = Float.parseFloat(txtfPrecio.getText());
    }//GEN-LAST:event_txtfPrecioKeyReleased

    public Date getFecha() {
        return fecha;
    }

    public String getConcepto() {
        return concepto;
    }

    public float getCantidad() {
        return cantidad;
    }

    public float getPrecio() {
        return precio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblConcepto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtfCantidad;
    private javax.swing.JTextField txtfConcepto;
    private javax.swing.JTextField txtfPrecio;
    // End of variables declaration//GEN-END:variables
}
