/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almazarabarcha.vista;

import almazarabarcha.Modelo.GestorAlmazara;
import almazarabarcha.estilos.Estilos;
import java.awt.Color;
import javax.swing.JPanel;
import pojos.Cambio;
import pojos.Proveedor;
import pojos.Usuario;

/**
 *
 * @author Ventura
 */
public class FinalizarCambio extends javax.swing.JFrame {

    private Cambio c;
    private JPanel jpanel;
    private Usuario u;
    private Proveedor p;
    private final Estilos estilos = new Estilos();
            
    
    /**
     * Creates new form FinalizarCambio
     */
    public FinalizarCambio(JPanel jpanel,Usuario u,Proveedor p,Cambio c) {
        initComponents();
        lb_costeCambio.setText(String.format("%.2f", c.getPrecioMolturacion()));
        lb_fecha.setText(c.getFecha().toString());
        lb_kgOliva.setText(String.format("%.2f",c.getKgOliva()));
        lb_porcent_maquila.setText(String.format("%.2f",c.getPorcentajeMaquila())+" %");
        lb_litros_maquila_reflejada.setText(String.format("%.2f",c.getMaquilaReflejada())+" L");
        lb_litros_para_cambio.setText(String.format("%.2f",c.getLitrosAceiteCambio())+" L");
        lb_litros_retirado.setText(String.format("%.2f",c.getLitrosAceiteRetirados())+" L");
        lb_maquila.setText(String.format("%.2f",c.getMaquila())+" L");
        lb_nomcliente.setText(c.getProveedor().getNombre());
        lb_rendimiento.setText(String.format("%.2f",c.getRendimiento())+" %");
        lb_usuario.setText(u.getNombre());
        this.c = c;
        this.u = u;
        this.jpanel = jpanel;
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_rendimiento = new javax.swing.JLabel();
        lb_porcentaje = new javax.swing.JLabel();
        lb_orujoTitulo = new javax.swing.JLabel();
        lb_litros_maquila_reflejada = new javax.swing.JLabel();
        lb_maquilaTitulo = new javax.swing.JLabel();
        lb_maquila = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_nomcliente = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_kgOliva = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_costeCambio = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lb_rendimientoTitulo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_rendimientoTitulo1 = new javax.swing.JLabel();
        lb_litros_retirado = new javax.swing.JLabel();
        lb_litros_para_cambio = new javax.swing.JLabel();
        lb_porcent_maquila = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_rendimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_rendimiento.setText("jLabel11");

        lb_porcentaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_porcentaje.setText("%");

        lb_orujoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_orujoTitulo.setText("Maquila reflejada:");

        lb_litros_maquila_reflejada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_litros_maquila_reflejada.setText("litros maqu refle");

        lb_maquilaTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_maquilaTitulo.setText("Maquila:");

        lb_maquila.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_maquila.setText("maquila");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Fecha: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cambio de: ");

        lb_nomcliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_nomcliente.setText("jLabel3");

        lb_fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fecha.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kg de Oliva molturada:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Usuario:");

        lb_kgOliva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_kgOliva.setText("jLabel4");

        lb_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_usuario.setText("jLabel11");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("COSTE TOTAL:");

        lb_costeCambio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb_costeCambio.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("€");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Litros de aceite para cambio:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Kg");

        lb_rendimientoTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_rendimientoTitulo.setText("Rendimiento:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Litros de aceite retirado:");

        lb_rendimientoTitulo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_rendimientoTitulo1.setText("Ref % Maquila: ");

        lb_litros_retirado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_litros_retirado.setText("litros retirado");

        lb_litros_para_cambio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_litros_para_cambio.setText("litros cambio");

        lb_porcent_maquila.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_porcent_maquila.setText("litros maquila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_rendimientoTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_rendimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_porcentaje))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_litros_retirado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_litros_para_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_orujoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_litros_maquila_reflejada, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(208, 208, 208)
                                        .addComponent(lb_maquilaTitulo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_maquila, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_costeCambio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lb_kgOliva, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_rendimientoTitulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_porcent_maquila, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_nomcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lb_usuario)
                    .addComponent(jLabel5)
                    .addComponent(lb_costeCambio)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_nomcliente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_fecha)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(lb_kgOliva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_litros_para_cambio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lb_litros_retirado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rendimientoTitulo)
                    .addComponent(lb_rendimiento)
                    .addComponent(lb_porcentaje))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rendimientoTitulo1)
                    .addComponent(lb_porcent_maquila))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_orujoTitulo)
                    .addComponent(lb_litros_maquila_reflejada)
                    .addComponent(lb_maquilaTitulo)
                    .addComponent(lb_maquila))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_costeCambio;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_kgOliva;
    private javax.swing.JLabel lb_litros_maquila_reflejada;
    private javax.swing.JLabel lb_litros_para_cambio;
    private javax.swing.JLabel lb_litros_retirado;
    private javax.swing.JLabel lb_maquila;
    private javax.swing.JLabel lb_maquilaTitulo;
    private javax.swing.JLabel lb_nomcliente;
    private javax.swing.JLabel lb_orujoTitulo;
    private javax.swing.JLabel lb_porcent_maquila;
    private javax.swing.JLabel lb_porcentaje;
    private javax.swing.JLabel lb_rendimiento;
    private javax.swing.JLabel lb_rendimientoTitulo;
    private javax.swing.JLabel lb_rendimientoTitulo1;
    private javax.swing.JLabel lb_usuario;
    // End of variables declaration//GEN-END:variables
}
