/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almazarabarcha.vista;

import capaDAO.DaoCliente;
import capaDAO.DaoGastos;
import capaDAO.DaoProveedor;
import excepciones.BusinessException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojos.Gastos;

/**
 *
 * @author Ventura
 */
public class GestionGastos extends javax.swing.JFrame {

    private List<Gastos> gastos = new ArrayList<>();

    /**
     * Creates new form GestionGastos
     */
    public GestionGastos() {
        initComponents();
        RellenaTabla();
        CalculaTotales();
    }

    private void RellenaTabla() {
        try {
            gastos = DaoGastos.getGastos();
        } catch (BusinessException ex) {
            Logger.getLogger(SeleccionarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        Object[] fila = new Object[7];
        DefaultTableModel modelo = (DefaultTableModel) tableGastos.getModel();
        int num_filas = modelo.getRowCount();
        for (int i = 0; i < num_filas; i++) {
            modelo.removeRow(0);
        }

        for (int i = 0; i < gastos.size(); i++) {
            fila[0] = gastos.get(i).getIdGasto();
            fila[1] = gastos.get(i).getFecha();
            fila[2] = gastos.get(i).getConcepto();
            fila[3] = gastos.get(i).getCantidad();
            fila[4] = gastos.get(i).getPrecio();
            fila[5] = gastos.get(i).getGastos();
            fila[6] = gastos.get(i).getManoObra();
            modelo.addRow(fila);
        }

        tableGastos.setModel(modelo);
    }

    private void CalculaTotales() {
        float importeGasto = 0;
        float manoObra = 0;
        float totalGastos = 0;

        for (Gastos gasto : gastos) {
            importeGasto += gasto.getGastos();
            manoObra += gasto.getManoObra();
        }

        totalGastos = importeGasto + manoObra;

        lblGasto.setText(String.format("%.2f €", importeGasto));
        lblManoObra.setText(String.format("%.2f €", manoObra));
        lblGastoTotal.setText(String.format("%.2f €", totalGastos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGastos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();
        lblManoObra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGastoTotal = new javax.swing.JLabel();
        btnGasto = new javax.swing.JButton();
        btnManoObra = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("GESTION DE GASTOS");

        tableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Concepto", "Cantidad", "Precio (€) ", "Gasto (€)", "Mano de Obra (€)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableGastos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Total Gasto:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total Mano de Obra:");

        lblGasto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGasto.setText("jLabel4");

        lblManoObra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManoObra.setText("jLabel5");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Gasto Total:");

        lblGastoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGastoTotal.setText("jLabel5");

        btnGasto.setText("Añadir Gasto");
        btnGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGastoActionPerformed(evt);
            }
        });

        btnManoObra.setText("Añadir Mano de Obra");
        btnManoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManoObraActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar Gasto");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManoObra, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblGastoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblGasto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblManoObra)
                    .addComponent(jLabel4)
                    .addComponent(lblGastoTotal))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGastoActionPerformed
        boolean ok;
        AñadirGasto ag = new AñadirGasto("Gasto", "Concepto:", "Precio:");
        if (JOptionPane.showConfirmDialog(null, ag, "Añadir gasto", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            Gastos g = new Gastos(ag.getFecha(), ag.getConcepto(), ag.getCantidad(), ag.getPrecio(), ag.getCantidad() * ag.getPrecio(), (float) 0);
            try {
                DaoGastos.insertar(g);
            } catch (BusinessException ex) {
                Logger.getLogger(GestionGastos.class.getName()).log(Level.SEVERE, null, ex);
            }
            RellenaTabla();
            CalculaTotales();
        }
    }//GEN-LAST:event_btnGastoActionPerformed

    private void btnManoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManoObraActionPerformed
        boolean ok;
        AñadirGasto ag = new AñadirGasto("Mano de Obra", "Empleado:", "Mano de Obra:");
        if (JOptionPane.showConfirmDialog(null, ag, "Añadir mano de obra", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            Gastos g = new Gastos(ag.getFecha(), ag.getConcepto(), ag.getCantidad(), 0, 0, ag.getPrecio());
            try {
                DaoGastos.insertar(g);
            } catch (BusinessException ex) {
                Logger.getLogger(GestionGastos.class.getName()).log(Level.SEVERE, null, ex);
            }
            RellenaTabla();
            CalculaTotales();
        }
    }//GEN-LAST:event_btnManoObraActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
            if (JOptionPane.showConfirmDialog(new JFrame(), "¿Está seguro que desea eliminar el gasto seleccionado?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int fila = tableGastos.getSelectedRow();
            boolean eliminado = false;
            try {
                
                   eliminado = DaoGastos.borrarGasto((int) tableGastos.getValueAt(fila, 0));
                
            } catch (BusinessException ex) {
                Logger.getLogger(GestionGastos.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (eliminado) {
                JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
            }
            RellenaTabla();
            CalculaTotales();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGasto;
    private javax.swing.JButton btnManoObra;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGasto;
    private javax.swing.JLabel lblGastoTotal;
    private javax.swing.JLabel lblManoObra;
    private javax.swing.JTable tableGastos;
    // End of variables declaration//GEN-END:variables
}
