package almazarabarcha.vista;

import capaDAO.DaoUsuario;
import com.sun.glass.events.KeyEvent;
import excepciones.BusinessException;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import pojos.Usuario;

public class Login extends javax.swing.JFrame {

    ImageIcon imagenFondo;
    Image img;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btn_gestionar_usuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btn_login.setText("Iniciar Sesion");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        btn_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_loginKeyReleased(evt);
            }
        });
        getContentPane().add(btn_login);
        btn_login.setBounds(252, 277, 134, 39);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 110, 60, 14);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 180, 80, 14);

        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_userKeyReleased(evt);
            }
        });
        getContentPane().add(txt_user);
        txt_user.setBounds(222, 97, 198, 37);

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
        });
        getContentPane().add(txt_pass);
        txt_pass.setBounds(222, 171, 198, 37);

        btn_gestionar_usuarios.setText("Gestionar usuarios");
        btn_gestionar_usuarios.setBorderPainted(false);
        btn_gestionar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionar_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestionar_usuarios);
        btn_gestionar_usuarios.setBounds(250, 370, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/almazarabarcha/estilos/almazara logo_bien.jpg"))); // NOI18N
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel3KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-60, 0, 730, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        EntrarEnter();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_gestionar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionar_usuariosActionPerformed
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Introduce contraseña de usuario:");
        JPasswordField pass = new JPasswordField(25);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Seguridad",
                
            JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE,
                null, options, options[0]);
        

        if (option == 0) // pressing OK button
        {
            String password = String.valueOf(pass.getPassword());
            try {
                if (DaoUsuario.isAdmin(password)) {
                    GestionUsuarios gu = new GestionUsuarios();
                    gu.setVisible(true);
                }
            } catch (BusinessException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_gestionar_usuariosActionPerformed

    private void jLabel3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyReleased
        

    }//GEN-LAST:event_jLabel3KeyReleased

    private void txt_userKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            EntrarEnter();
        }
    }//GEN-LAST:event_txt_userKeyReleased

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            EntrarEnter();
        }
    }//GEN-LAST:event_txt_passKeyReleased

    private void btn_loginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_loginKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            EntrarEnter();
        }
    }//GEN-LAST:event_btn_loginKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            Login l;
            l = new Login();
            l.setVisible(true);
            l.setLocation(300, 150);
            l.setSize(650, 440);
        });
    }
    
    private void EntrarEnter(){
       
            Usuario u;
            try {
                if (DaoUsuario.isUsuario(txt_user.getText(), String.valueOf(txt_pass.getPassword()))) {
                    u = DaoUsuario.getUsuario(txt_user.getText());
                    MenuPrincipal menu = new MenuPrincipal(u);
                    menu.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario o la contraseña son incorrectos");
                }
            } catch (BusinessException | IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gestionar_usuarios;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
