-- MySQL Script generated by MySQL Workbench
-- 10/17/16 15:27:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema almazaradb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `almazaradb` ;

-- -----------------------------------------------------
-- Schema almazaradb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `almazaradb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `almazaradb` ;

-- -----------------------------------------------------
-- Table `almazaradb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `dni` VARCHAR(9) NULL COMMENT '',
  `direccion` VARCHAR(70) NULL COMMENT '',
  `telefono` VARCHAR(9) NULL COMMENT '',
  `poblacion` VARCHAR(25) NULL COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NOT NULL COMMENT '',
  `contrasenya` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NOT NULL COMMENT '',
  `dni` VARCHAR(9) NULL COMMENT '',
  `direccion` VARCHAR(70) NULL COMMENT '',
  `telefono` VARCHAR(9) NULL COMMENT '',
  `poblacion` VARCHAR(25) NULL COMMENT '',
  `subvencionado` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idProveedor`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Molturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Molturacion` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Molturacion` (
  `idMolturacion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `kgOliva` FLOAT NOT NULL COMMENT '',
  `litrosAceiteProd` FLOAT NOT NULL COMMENT '',
  `kgAceiteProd` FLOAT NULL COMMENT '',
  `kgOrujo` FLOAT NOT NULL COMMENT '',
  `ingresoMolturacion` FLOAT NOT NULL COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `Pagada` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `declara` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `kgReflejadosDeclaracion` FLOAT NOT NULL COMMENT '',
  `maquila` FLOAT NOT NULL COMMENT '',
  `Observaciones` VARCHAR(100) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `Proveedor_idProveedor` INT NOT NULL COMMENT '',
  `rendimiento` FLOAT NOT NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idMolturacion`)  COMMENT '',
  INDEX `fk_Molturacion_Usuario1_idx` (`Usuario_idUsuario` ASC)  COMMENT '',
  INDEX `fk_Molturacion_Proveedor1_idx` (`Proveedor_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Molturacion_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `almazaradb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Molturacion_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `almazaradb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `factura` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `regalo` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `otro` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `totalVenta` FLOAT NOT NULL COMMENT '',
  `Observaciones` VARCHAR(100) NULL COMMENT '',
  `litrosDeclarables` FLOAT NOT NULL COMMENT '',
  `Cliente_idCliente` INT NOT NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idVenta`)  COMMENT '',
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_idCliente` ASC)  COMMENT '',
  INDEX `fk_Venta_Usuario1_idx` (`Usuario_idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `almazaradb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `almazaradb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Compra` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `kgOliva` FLOAT NOT NULL COMMENT '',
  `precioKg` FLOAT NOT NULL COMMENT '',
  `totalCompra` FLOAT NOT NULL COMMENT '',
  `pagado` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `declara` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `factura` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `maquilaReflejada` FLOAT NOT NULL COMMENT '',
  `observaciones` VARCHAR(100) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `Proveedor_idProveedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCompra`)  COMMENT '',
  INDEX `fk_Compra_Usuario1_idx` (`Usuario_idUsuario` ASC)  COMMENT '',
  INDEX `fk_Compra_Proveedor1_idx` (`Proveedor_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Compra_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `almazaradb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `almazaradb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Cambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Cambio` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Cambio` (
  `idCambio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `kgOliva` FLOAT NOT NULL COMMENT '',
  `paga` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `retira` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `rendimiento` FLOAT NOT NULL COMMENT '',
  `litrosAceiteCambio` FLOAT NOT NULL COMMENT '',
  `kgAceiteCambio` FLOAT NULL COMMENT '',
  `litrosAceiteRetirados` FLOAT NOT NULL COMMENT '',
  `kgAceiteRetirados` FLOAT NULL COMMENT '',
  `porcentajeMaquila` FLOAT NOT NULL COMMENT '',
  `maquila` FLOAT NOT NULL COMMENT '',
  `precioMolturacion` FLOAT NOT NULL COMMENT '',
  `totalPagar` FLOAT NOT NULL COMMENT '',
  `maquilaReflejada` FLOAT NOT NULL COMMENT '',
  `kgOlivaReflejados` FLOAT NOT NULL COMMENT '',
  `poblacionOliva` VARCHAR(30) NULL COMMENT '',
  `Observaciones` VARCHAR(100) NULL COMMENT '',
  `Usuario_idUsuario` INT NOT NULL COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `declara` TINYINT(1) NOT NULL COMMENT '',
  `Proveedor_idProveedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCambio`)  COMMENT '',
  INDEX `fk_Cambio_Usuario1_idx` (`Usuario_idUsuario` ASC)  COMMENT '',
  INDEX `fk_Cambio_Proveedor1_idx` (`Proveedor_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Cambio_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `almazaradb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cambio_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `almazaradb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`idProducto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Venta_has_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Venta_has_Producto` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Venta_has_Producto` (
  `Venta_idVenta` INT NOT NULL COMMENT '',
  `Producto_idProducto` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio` FLOAT NOT NULL COMMENT '',
  `precioTotal` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`Venta_idVenta`, `Producto_idProducto`)  COMMENT '',
  INDEX `fk_Venta_has_Producto_Producto1_idx` (`Producto_idProducto` ASC)  COMMENT '',
  INDEX `fk_Venta_has_Producto_Venta1_idx` (`Venta_idVenta` ASC)  COMMENT '',
  CONSTRAINT `fk_Venta_has_Producto_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `almazaradb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `almazaradb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almazaradb`.`Gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `almazaradb`.`Gastos` ;

CREATE TABLE IF NOT EXISTS `almazaradb`.`Gastos` (
  `idGasto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha` DATETIME NOT NULL COMMENT '',
  `concepto` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad` FLOAT NOT NULL COMMENT '',
  `precio` FLOAT NULL COMMENT '',
  `gastos` FLOAT NOT NULL DEFAULT 0 COMMENT '',
  `manoObra` FLOAT NULL COMMENT '',
  PRIMARY KEY (`idGasto`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
